resolver: lts-7.15

extra-deps:
  - heist-1.0.1.0
  - map-syntax-0.2.0.1

packages:
  - digestive-functors/
  - digestive-functors-blaze/
  - digestive-functors-happstack/
  - digestive-functors-heist/
  - digestive-functors-snap/
